spring:
  mail:
    username: fw940314@foxmail.com
    password: clzotjwzysgvbjaa
    host: smtp.qq.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true
           
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl  

 ip:
  limited:
    limit: 10
    time: 1000
